# Generated by Django 4.2.1 on 2024-02-17 00:27

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("job_title", models.CharField(max_length=50)),
                (
                    "company_logo",
                    models.ImageField(blank=True, null=True, upload_to="logo"),
                ),
                ("company_name", models.CharField(max_length=60)),
                ("location", models.CharField(max_length=60)),
                ("post_code", models.CharField(max_length=6)),
                ("job_description", ckeditor.fields.RichTextField()),
                ("pay_rate", models.CharField(max_length=50)),
                ("job_image_one", models.ImageField(upload_to="job_image")),
                ("job_image_two", models.ImageField(upload_to="job_image")),
                ("job_image_three", models.ImageField(upload_to="job_image")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updater_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
