# Generated by Django 4.2.1 on 2024-02-17 00:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobpost", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_description",
            field=ckeditor.fields.RichTextField(max_length=2000),
        ),
    ]
