# Generated by Django 4.2.10 on 2024-02-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0002_alter_job_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='pay_rate',
            field=models.CharField(default='£', max_length=50),
        ),
    ]
