# Generated by Django 4.2.10 on 2024-02-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0003_alter_job_pay_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_image_one',
            field=models.ImageField(blank=True, null=True, upload_to='job_image'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_image_three',
            field=models.ImageField(blank=True, null=True, upload_to='job_image'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_image_two',
            field=models.ImageField(blank=True, null=True, upload_to='job_image'),
        ),
    ]
