# Generated by Django 4.2.10 on 2024-03-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0006_starredjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='starredjob',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
